In [1]:
import pandas as pd 
import time
import random
import os
from utils import get_data,data_processing
from datetime import datetime
import uuid

In [2]:
url = ['https://www.espn.com.co/futbol/posiciones/_/liga/esp.1',
      'https://www.espn.com.co/futbol/posiciones/_/liga/eng.1',
      'https://www.espn.com.co/futbol/posiciones/_/liga/ita.1',
      'https://www.espn.com.co/futbol/posiciones/_/liga/ger.1',
      'https://www.espn.com.co/futbol/posiciones/_/liga/fra.1',
      'https://www.espn.com.co/futbol/posiciones/_/liga/por.1',
      'https://www.espn.com.co/futbol/posiciones/_/liga/ned.1']
ligas = ['ESPAÑA','INGLATERRA','ITALIA','ALEMANIA','FRANCIA','PORTUGAL','HOLANDA']

df_ligas = {
    'LIGA':ligas,
    'URL':url
} 

df_ligas = pd.DataFrame(df_ligas)
df_ligas

         LIGA                                                URL
0      ESPAÑA  https://www.espn.com.co/futbol/posiciones/_/li...
1  INGLATERRA  https://www.espn.com.co/futbol/posiciones/_/li...
2      ITALIA  https://www.espn.com.co/futbol/posiciones/_/li...
3    ALEMANIA  https://www.espn.com.co/futbol/posiciones/_/li...
4     FRANCIA  https://www.espn.com.co/futbol/posiciones/_/li...
5    PORTUGAL  https://www.espn.com.co/futbol/posiciones/_/li...
6     HOLANDA  https://www.espn.com.co/futbol/posiciones/_/li...

In [3]:
df_ligas['URL'][1]

'https://www.espn.com.co/futbol/posiciones/_/liga/eng.1'

In [4]:
df = pd.read_html(df_ligas['URL'][1])

In [5]:
len(df)

2

In [6]:
df[0]

                     2026/2027
0          1BOUAFC Bournemouth
1                  2ARSArsenal
2              3AVLAston Villa
3                4BRNBrentford
4   5BHABrighton & Hove Albion
5                  6CHEChelsea
6       7CoventryCoventry City
7           8CRYCrystal Palace
8                  9EVEEverton
9                  10FULFulham
10              11HCYHull City
11           12IPSIpswich Town
12           13LEELeeds United
13              14LIVLiverpool
14        15MCIManchester City
15      16MUNManchester United
16       17NEWNewcastle United
17      18FORNottingham Forest
18             19SUNSunderland
19      20TOTTottenham Hotspur

In [7]:
df[1]

    J  G  E  P  GF  GC  DIF  PTS
0   0  0  0  0   0   0    0    0
1   0  0  0  0   0   0    0    0
2   0  0  0  0   0   0    0    0
3   0  0  0  0   0   0    0    0
4   0  0  0  0   0   0    0    0
5   0  0  0  0   0   0    0    0
6   0  0  0  0   0   0    0    0
7   0  0  0  0   0   0    0    0
8   0  0  0  0   0   0    0    0
9   0  0  0  0   0   0    0    0
10  0  0  0  0   0   0    0    0
11  0  0  0  0   0   0    0    0
12  0  0  0  0   0   0    0    0
13  0  0  0  0   0   0    0    0
14  0  0  0  0   0   0    0    0
15  0  0  0  0   0   0    0    0
16  0  0  0  0   0   0    0    0
17  0  0  0  0   0   0    0    0
18  0  0  0  0   0   0    0    0
19  0  0  0  0   0   0    0    0

In [8]:
df=pd.concat([df[0],df[1]],ignore_index=True,axis=1)
df

                             0  1  2  3  4  5  6  7  8
0          1BOUAFC Bournemouth  0  0  0  0  0  0  0  0
1                  2ARSArsenal  0  0  0  0  0  0  0  0
2              3AVLAston Villa  0  0  0  0  0  0  0  0
3                4BRNBrentford  0  0  0  0  0  0  0  0
4   5BHABrighton & Hove Albion  0  0  0  0  0  0  0  0
5                  6CHEChelsea  0  0  0  0  0  0  0  0
6       7CoventryCoventry City  0  0  0  0  0  0  0  0
7           8CRYCrystal Palace  0  0  0  0  0  0  0  0
8                  9EVEEverton  0  0  0  0  0  0  0  0
9                  10FULFulham  0  0  0  0  0  0  0  0
10              11HCYHull City  0  0  0  0  0  0  0  0
11           12IPSIpswich Town  0  0  0  0  0  0  0  0
12           13LEELeeds United  0  0  0  0  0  0  0  0
13              14LIVLiverpool  0  0  0  0  0  0  0  0
14        15MCIManchester City  0  0  0  0  0  0  0  0
15      16MUNManchester United  0  0  0  0  0  0  0  0
16       17NEWNewcastle United  0  0  0  0  0  0  0  0
17      18FORNottingham Forest  0  0  0  0  0  0  0  0
18             19SUNSunderland  0  0  0  0  0  0  0  0
19      20TOTTottenham Hotspur  0  0  0  0  0  0  0  0

In [9]:
df=df.rename(columns={0:'EQUIPO',1:'J', 2:'G', 3:'E', 4:'P', 5:'GF', 6:'GC', 7:'DIF', 8:'PTS'})
df['EQUIPO']=df['EQUIPO'].apply(lambda x: x[5:] if x[:2].isnumeric()==True else x[4:])
df['LIGA'] = df_ligas['LIGA'][1]

In [10]:
df

                    EQUIPO  J  G  E  P  GF  GC  DIF  PTS        LIGA
0          AFC Bournemouth  0  0  0  0   0   0    0    0  INGLATERRA
1                  Arsenal  0  0  0  0   0   0    0    0  INGLATERRA
2              Aston Villa  0  0  0  0   0   0    0    0  INGLATERRA
3                Brentford  0  0  0  0   0   0    0    0  INGLATERRA
4   Brighton & Hove Albion  0  0  0  0   0   0    0    0  INGLATERRA
5                  Chelsea  0  0  0  0   0   0    0    0  INGLATERRA
6       entryCoventry City  0  0  0  0   0   0    0    0  INGLATERRA
7           Crystal Palace  0  0  0  0   0   0    0    0  INGLATERRA
8                  Everton  0  0  0  0   0   0    0    0  INGLATERRA
9                   Fulham  0  0  0  0   0   0    0    0  INGLATERRA
10               Hull City  0  0  0  0   0   0    0    0  INGLATERRA
11            Ipswich Town  0  0  0  0   0   0    0    0  INGLATERRA
12            Leeds United  0  0  0  0   0   0    0    0  INGLATERRA
13               Liverpool  0  0  0  0   0   0    0    0  INGLATERRA
14         Manchester City  0  0  0  0   0   0    0    0  INGLATERRA
15       Manchester United  0  0  0  0   0   0    0    0  INGLATERRA
16        Newcastle United  0  0  0  0   0   0    0    0  INGLATERRA
17       Nottingham Forest  0  0  0  0   0   0    0    0  INGLATERRA
18              Sunderland  0  0  0  0   0   0    0    0  INGLATERRA
19       Tottenham Hotspur  0  0  0  0   0   0    0    0  INGLATERRA

In [11]:
df_ligas.to_csv('df_ligas.csv',index=False)

In [12]:
def id_generator(team):

    return str(uuid.uuid1())[:8]

In [13]:
id_generator('carro')

'83837f5c'

In [14]:
id_generator('gato')

'8384a60c'

In [15]:
lista_resultado = 0

In [16]:
equipos = df_hola['EQUIPO'].unique()
lista_resultado = list(map(id_generator, equipos))

NameError: name 'df_hola' is not defined

In [ ]:
team_table = {

    'EQUIPO':equipos,
    'ID_TEAM':lista_resultado
}

df_team = pd.DataFrame(team_table)

In [ ]:
df_team['ID_TEAM'].value_counts()

In [ ]:
df_team.to_csv('team_table.csv',index=False)

In [ ]:
pd.read_csv('df_ligas.csv')

In [ ]:
df_final = pd.merge(df_hola,df_team,how='inner',on='EQUIPO')
df_final.columns
df_final = df_final[['ID_TEAM','EQUIPO', 'J', 'G', 'E', 'P', 'GF', 'GC', 'DIF', 'PTS', 'LIGA',
       'CREATED_AT']]
df_final

In [ ]:
df_final.to_csv('premier_positions.csv',index=False)

In [ ]:
lista_resultado[0]

In [ ]:
hash('hola')

In [ ]:
df_hola

In [ ]:
import re

def clean_team_name(team_name):
    return re.sub(r"^\d+[A-Z]{3}", "", team_name)

In [ ]:
raw = pd.read_html(
    "https://www.espn.com.co/futbol/posiciones/_/liga/eng.1"
)

teams = pd.concat(
    [raw[0], raw[1]],
    ignore_index=True,
    axis=1
)[0]

for team in teams:
    print(team, "→", clean_team_name(team))

In [ ]:
raw = pd.read_html(
    "https://www.espn.com.co/futbol/posiciones/_/liga/eng.1"
)

print(raw[0].columns)
print(raw[1].columns)

In [ ]:
print(raw[0].head())
print(raw[1].head())

In [19]:
leagues = pd.read_csv("df_ligas.csv")

for _, row in leagues.iterrows():
    print(f"\n===== {row['LIGA']} =====")

    raw = pd.read_html(row["URL"])
    teams = pd.concat(
        [raw[0], raw[1]],
        ignore_index=True,
        axis=1
    )[0]

    for team in teams:
        print(team)

===== ESPAÑA =====
1ALAAlavés
2ATHAthletic Club
3ATLAtlético de Madrid
4BARBarcelona
5VIGCelta Vigo
6DEPDeportivo La Coruña
7ELCElche
8ESPEspanyol
9GETGetafe
10LEVLevante
11MGAMálaga
12OSAOsasuna
13RACRacing Santander
14RAYRayo Vallecano
15BETReal Betis
16MADReal Madrid
17SOCReal Sociedad
18SEVSevilla FC
19VALValencia
20VLRVillarreal

===== INGLATERRA =====
1BOUAFC Bournemouth
2ARSArsenal
3AVLAston Villa
4BRNBrentford
5BHABrighton & Hove Albion
6CHEChelsea
7CoventryCoventry City
8CRYCrystal Palace
9EVEEverton
10FULFulham
11HCYHull City
12IPSIpswich Town
13LEELeeds United
14LIVLiverpool
15MCIManchester City
16MUNManchester United
17NEWNewcastle United
18FORNottingham Forest
19SUNSunderland
20TOTTottenham Hotspur

===== ITALIA =====
1MILAC Milan
2ATAAtalanta
3BOLBolonia
4CAGCagliari
5COMOComo
6FIOFiorentina
7FROFrosinone
8GENGénova
9INTInternazionale
10JUVJuventus
11LAZLazio
12LECLecce
13MONMonza
14NAPNapoli
15PARParma
16ROMAS Roma
17SASSassuolo
18TORTorino
19UDIUdinese
20VENVenezia

===== ALEMANIA =====
1AUGF. C. Augsburgo
2LEVBayer Leverkusen
3BMUBayern Munich
4DORBorussia Dortmund
5MGBBorussia Monchengladbach
6FRAEintracht Frankfurt
7ELVSV Elversberg
8KOEFC Cologne
9SCFSC Freiburg
10HSVHamburg SV
11TSGTSG Hoffenheim
12M05Mainz
13PADSC Paderborn 07
14RBLRB Leipzig
15S04Schalke 04
16VFBVfB Stuttgart
17FCU1. FC Union Berlin
18BREWerder Bremen

===== FRANCIA =====
1ANGAngers
2AUXAJ Auxerre
3BRSBrest
4Le Havre ACLe Havre AC
5MNSLe Mans
6LNSLens
7LILLLille
8LORLorient
9LYONLyon
10OLMMarseille
11MONAS Mónaco
12NICENice
13Paris FCParis FC
14PSGParis Saint-Germain
15RENStade Rennais
16STRStrasbourg
17TOUToulouse
18TRYTroyes

===== PORTUGAL =====
1SCPSporting CP
2FCPFC Porto
3FCAArouca
4GVFCGil Vicente
5MARMaritimo
6ESTEstrela
7ACVAcadémico de Viseu
8BENBenfica
9MFCMoreirense
10CDNC.D. Nacional
11CDSCSanta Clara
12SCBBraga
13EPFEstoril
14FCFFC Famalicao
15ALVAlverca
16CPACCasa Pia
17RAFCRio Ave
18VSCVitória de Guimaraes

===== HOLANDA =====
1EXCExcelsior
2Go AheadGo Ahead Eagles
3AZAZ Alkmaar
4AJAXAjax Amsterdam
5GROFC Groningen
6FEYFeyenoord Rotterdam
7HEEHeerenveen
8NECNEC Nijmegen
9Sp RotterdamSparta Rotterdam
10TELTelstar
11FortunaFortuna Sittard
12PSVPSV Eindhoven
13UTRFC Utrecht
14TWEFC Twente
15ADOADO Den Haag
16PECPEC Zwolle
17CAMSC Cambuur
18WILWillem II

In [20]:
import re


def clean_team_name(team_name):
    # Remove the position number
    team_name = re.sub(r"^\d+", "", team_name)

    # Handle 4-letter codes that repeat the beginning of the team name
    match = re.match(r"^([A-Z]{4})([A-Z][a-z].*)$", team_name)

    if match and match.group(1).lower() == match.group(2)[:4].lower():
        team_name = match.group(2)

    # Remove 3-letter ESPN codes
    elif re.search(r"^[A-Z]{3}[A-Z]", team_name):
        team_name = team_name[3:]

    else:
        # Handle repeated team names
        for i in range(1, len(team_name)):
            first_part = team_name[:i]
            second_part = team_name[i:]

            if second_part.startswith(first_part):
                team_name = second_part
                break

    return team_name.strip()

In [21]:
for _, row in leagues.iterrows():
    print(f"\n===== {row['LIGA']} =====")

    raw = pd.read_html(row["URL"])

    teams = pd.concat(
        [raw[0], raw[1]],
        ignore_index=True,
        axis=1
    )[0]

    for team in teams:
        print(f"{team} → {clean_team_name(team)}")

===== ESPAÑA =====
1ALAAlavés → Alavés
2ATHAthletic Club → Athletic Club
3ATLAtlético de Madrid → Atlético de Madrid
4BARBarcelona → Barcelona
5VIGCelta Vigo → Celta Vigo
6DEPDeportivo La Coruña → Deportivo La Coruña
7ELCElche → Elche
8ESPEspanyol → Espanyol
9GETGetafe → Getafe
10LEVLevante → Levante
11MGAMálaga → Málaga
12OSAOsasuna → Osasuna
13RACRacing Santander → Racing Santander
14RAYRayo Vallecano → Rayo Vallecano
15BETReal Betis → Real Betis
16MADReal Madrid → Real Madrid
17SOCReal Sociedad → Real Sociedad
18SEVSevilla FC → Sevilla FC
19VALValencia → Valencia
20VLRVillarreal → Villarreal

===== INGLATERRA =====
1BOUAFC Bournemouth → AFC Bournemouth
2ARSArsenal → Arsenal
3AVLAston Villa → Aston Villa
4BRNBrentford → Brentford
5BHABrighton & Hove Albion → Brighton & Hove Albion
6CHEChelsea → Chelsea
7CoventryCoventry City → Coventry City
8CRYCrystal Palace → Crystal Palace
9EVEEverton → Everton
10FULFulham → Fulham
11HCYHull City → Hull City
12IPSIpswich Town → Ipswich Town
13LEELeeds United → Leeds United
14LIVLiverpool → Liverpool
15MCIManchester City → Manchester City
16MUNManchester United → Manchester United
17NEWNewcastle United → Newcastle United
18FORNottingham Forest → Nottingham Forest
19SUNSunderland → Sunderland
20TOTTottenham Hotspur → Tottenham Hotspur

===== ITALIA =====
1MILAC Milan → AC Milan
2ATAAtalanta → Atalanta
3BOLBolonia → Bolonia
4CAGCagliari → Cagliari
5COMOComo → Como
6FIOFiorentina → Fiorentina
7FROFrosinone → Frosinone
8GENGénova → Génova
9INTInternazionale → Internazionale
10JUVJuventus → Juventus
11LAZLazio → Lazio
12LECLecce → Lecce
13MONMonza → Monza
14NAPNapoli → Napoli
15PARParma → Parma
16ROMAS Roma → AS Roma
17SASSassuolo → Sassuolo
18TORTorino → Torino
19UDIUdinese → Udinese
20VENVenezia → Venezia

===== ALEMANIA =====
1AUGF. C. Augsburgo → F. C. Augsburgo
2LEVBayer Leverkusen → Bayer Leverkusen
3BMUBayern Munich → Bayern Munich
4DORBorussia Dortmund → Borussia Dortmund
5MGBBorussia Monchengladbach → Borussia Monchengladbach
6FRAEintracht Frankfurt → Eintracht Frankfurt
7ELVSV Elversberg → SV Elversberg
8KOEFC Cologne → FC Cologne
9SCFSC Freiburg → SC Freiburg
10HSVHamburg SV → Hamburg SV
11TSGTSG Hoffenheim → TSG Hoffenheim
12M05Mainz → M05Mainz
13PADSC Paderborn 07 → SC Paderborn 07
14RBLRB Leipzig → RB Leipzig
15S04Schalke 04 → S04Schalke 04
16VFBVfB Stuttgart → VfB Stuttgart
17FCU1. FC Union Berlin → FCU1. FC Union Berlin
18BREWerder Bremen → Werder Bremen

===== FRANCIA =====
1ANGAngers → Angers
2AUXAJ Auxerre → AJ Auxerre
3BRSBrest → Brest
4Le Havre ACLe Havre AC → Le Havre AC
5MNSLe Mans → Le Mans
6LNSLens → Lens
7LILLLille → Lille
8LORLorient → Lorient
9LYONLyon → Lyon
10OLMMarseille → Marseille
11MONAS Mónaco → AS Mónaco
12NICENice → Nice
13Paris FCParis FC → Paris FC
14PSGParis Saint-Germain → Paris Saint-Germain
15RENStade Rennais → Stade Rennais
16STRStrasbourg → Strasbourg
17TOUToulouse → Toulouse
18TRYTroyes → Troyes

===== PORTUGAL =====
1SCPSporting CP → Sporting CP
2FCPFC Porto → FC Porto
3FCAArouca → Arouca
4GVFCGil Vicente → CGil Vicente
5MARMaritimo → Maritimo
6ESTEstrela → Estrela
7ACVAcadémico de Viseu → Académico de Viseu
8BENBenfica → Benfica
9MFCMoreirense → Moreirense
10CDNC.D. Nacional → C.D. Nacional
11CDSCSanta Clara → CSanta Clara
12SCBBraga → Braga
13EPFEstoril → Estoril
14FCFFC Famalicao → FC Famalicao
15ALVAlverca → Alverca
16CPACCasa Pia → CCasa Pia
17RAFCRio Ave → CRio Ave
18VSCVitória de Guimaraes → Vitória de Guimaraes

===== HOLANDA =====
1EXCExcelsior → Excelsior
2Go AheadGo Ahead Eagles → Go Ahead Eagles
3AZAZ Alkmaar → Z Alkmaar
4AJAXAjax Amsterdam → Ajax Amsterdam
5GROFC Groningen → FC Groningen
6FEYFeyenoord Rotterdam → Feyenoord Rotterdam
7HEEHeerenveen → Heerenveen
8NECNEC Nijmegen → NEC Nijmegen
9Sp RotterdamSparta Rotterdam → Sp RotterdamSparta Rotterdam
10TELTelstar → Telstar
11FortunaFortuna Sittard → Fortuna Sittard
12PSVPSV Eindhoven → PSV Eindhoven
13UTRFC Utrecht → FC Utrecht
14TWEFC Twente → FC Twente
15ADOADO Den Haag → ADO Den Haag
16PECPEC Zwolle → PEC Zwolle
17CAMSC Cambuur → SC Cambuur
18WILWillem II → Willem II

In [ ]:
teams = []

for _, row in leagues.iterrows():
    raw = pd.read_html(row["URL"])

    df_league = pd.concat(
        [raw[0], raw[1]],
        ignore_index=True,
        axis=1
    )

    for team in df_league[0]:
        teams.append(clean_team_name(team))

In [ ]:
team_table = pd.DataFrame({
    "EQUIPO": sorted(set(teams))
})

In [ ]:
team_table.shape

In [ ]:
team_table

In [ ]:
team_table[~team_table["EQUIPO"].str.match(r"^[A-Za-zÁÉÍÓÚáéíóúÑñÜü& .'-]+$")]

In [ ]:
team_table["EQUIPO"].str.lower().duplicated().sum()

In [ ]:
team_table["EQUIPO"].str.lower().duplicated().sum()

In [24]:
import importlib
import utils

importlib.reload(utils)

from utils import build_team_table

In [25]:
team_table = build_team_table(leagues)

In [26]:
team_table.shape

(132, 2)

In [27]:
team_table.head()

            EQUIPO   ID_TEAM
0         AC Milan  f47d7d57
1     ADO Den Haag  6971f0c8
2  AFC Bournemouth  3724f86e
3       AJ Auxerre  ea6f691f
4        AS Mónaco  3b0445c0

In [38]:
team_table.to_csv("team_table.csv", index=False)

In [42]:
data = []

for _, row in leagues.iterrows():
    raw = pd.read_html(row["URL"])

    df_league = pd.concat(
        [raw[0], raw[1]],
        ignore_index=True,
        axis=1
    )

    for team in df_league[0]:
        data.append({
            "EQUIPO": clean_team_name(team),
            "LIGA": row["LIGA"]
        })

df_all = pd.DataFrame(data)

In [43]:
df_all["LIGA"].value_counts()

LIGA
ESPAÑA        20
INGLATERRA    20
ITALIA        20
ALEMANIA      18
FRANCIA       18
PORTUGAL      18
HOLANDA       18
Name: count, dtype: int64

In [44]:
df_all["LIGA"].value_counts()

LIGA
ESPAÑA        20
INGLATERRA    20
ITALIA        20
ALEMANIA      18
FRANCIA       18
PORTUGAL      18
HOLANDA       18
Name: count, dtype: int64

In [45]:
df_final = pd.merge(
    df_all,
    team_table,
    how="inner",
    on="EQUIPO"
)

In [46]:
df_final["LIGA"].value_counts()

LIGA
ESPAÑA        20
INGLATERRA    20
ITALIA        20
ALEMANIA      18
FRANCIA       18
PORTUGAL      18
HOLANDA       18
Name: count, dtype: int64

In [5]:
import importlib
import utils

importlib.reload(utils)

In [62]:
from utils import clean_team_name, build_team_table, get_data, data_processing

In [63]:
test_teams = [
    "1ALAAlavés",
    "7CoventryCoventry City",
    "1COMOComo",
    "1AUGF. C. Augsburgo",
    "10M05Mainz",
    "3AZAZ Alkmaar",
    "2Go AheadGo Ahead Eagles"
]

for team in test_teams:
    print(f"{team} → {clean_team_name(team)}")

1ALAAlavés → Alavés
7CoventryCoventry City → Coventry City
1COMOComo → Como
1AUGF. C. Augsburgo → F. C. Augsburgo
10M05Mainz → M05Mainz
3AZAZ Alkmaar → Z Alkmaar
2Go AheadGo Ahead Eagles → Go Ahead Eagles

In [64]:
row = leagues.iloc[0]

df_test = get_data(
    row["URL"],
    row["LIGA"]
)

In [65]:
df_test.head()

               EQUIPO  J  G  E  P  GF  GC  DIF  PTS    LIGA  CREATED_AT
0              Alavés  0  0  0  0   0   0    0    0  ESPAÑA  2026-08-15
1       Athletic Club  0  0  0  0   0   0    0    0  ESPAÑA  2026-08-15
2  Atlético de Madrid  0  0  0  0   0   0    0    0  ESPAÑA  2026-08-15
3           Barcelona  0  0  0  0   0   0    0    0  ESPAÑA  2026-08-15
4          Celta Vigo  0  0  0  0   0   0    0    0  ESPAÑA  2026-08-15

In [66]:
df_test["LIGA"].unique()

<StringArray>
['ESPAÑA']
Length: 1, dtype: str

In [67]:
df_test["EQUIPO"].tolist()

['Alavés',
 'Athletic Club',
 'Atlético de Madrid',
 'Barcelona',
 'Celta Vigo',
 'Deportivo La Coruña',
 'Elche',
 'Espanyol',
 'Getafe',
 'Levante',
 'Málaga',
 'Osasuna',
 'Racing Santander',
 'Rayo Vallecano',
 'Real Betis',
 'Real Madrid',
 'Real Sociedad',
 'Sevilla FC',
 'Valencia',
 'Villarreal']

In [68]:
df = data_processing(leagues)

In [69]:
df["LIGA"].value_counts()

LIGA
ESPAÑA        20
INGLATERRA    20
ITALIA        20
ALEMANIA      18
FRANCIA       18
PORTUGAL      18
HOLANDA       18
Name: count, dtype: int64

In [70]:
df["EQUIPO"].nunique()

132

In [71]:
team_table = pd.read_csv("team_table.csv")

df_final = pd.merge(
    df,
    team_table,
    how="inner",
    on="EQUIPO"
)

df_final["LIGA"].value_counts()

LIGA
ESPAÑA        20
INGLATERRA    20
ITALIA        20
ALEMANIA      18
FRANCIA       18
PORTUGAL      18
HOLANDA       18
Name: count, dtype: int64

In [72]:
df_final.shape

(132, 12)

In [73]:
df_final.columns.tolist()

['EQUIPO',
 'J',
 'G',
 'E',
 'P',
 'GF',
 'GC',
 'DIF',
 'PTS',
 'LIGA',
 'CREATED_AT',
 'ID_TEAM']

In [11]:
import pandas as pd
from utils import build_team_table

leagues = pd.read_csv("df_ligas.csv")
team_table = pd.read_csv("team_table.csv")

new_team_table = build_team_table(
    leagues,
    existing_team_table=team_table
)

print(new_team_table.shape)

(132, 2)

In [12]:
comparison = team_table.merge(
    new_team_table,
    on="EQUIPO",
    suffixes=("_old", "_new")
)

print((comparison["ID_TEAM_old"] != comparison["ID_TEAM_new"]).sum())

0

In [13]:
test_team_table = team_table.iloc[1:].copy()

new_test_table = build_team_table(
    leagues,
    existing_team_table=test_team_table
)

missing_team = team_table.iloc[0]["EQUIPO"]

print(new_test_table[new_test_table["EQUIPO"] == missing_team])

     EQUIPO   ID_TEAM
0  AC Milan  2bd22b3a

In [14]:
team_table = pd.read_csv("team_table.csv")

print("¿Como está en el CSV?")
print("Como" in team_table["EQUIPO"].values)

print("\n¿Como está en la tabla generada?")
print("Como" in new_team_table["EQUIPO"].values)

¿Como está en el CSV?
False

¿Como está en la tabla generada?
True

In [15]:
team_table = pd.read_csv("team_table.csv")

new_team_table = build_team_table(
    leagues,
    existing_team_table=team_table
)

In [16]:
print(new_team_table[new_team_table["EQUIPO"] == "Como"])

   EQUIPO   ID_TEAM
36   Como  5160ad0d

In [17]:
team_table = pd.read_csv("team_table.csv")

new_team_table = build_team_table(
    leagues,
    existing_team_table=team_table
)

print(new_team_table.shape)

comparison = team_table.merge(
    new_team_table,
    on="EQUIPO",
    suffixes=("_old", "_new")
)

print(
    "IDs modificados:",
    (comparison["ID_TEAM_old"] != comparison["ID_TEAM_new"]).sum()
)

(132, 2)
IDs modificados: 0

In [18]:
new_team_table.to_csv("team_table.csv", index=False)

In [19]:
saved_team_table = pd.read_csv("team_table.csv")

print(saved_team_table.shape)
print(saved_team_table.equals(new_team_table))

(132, 2)
True